---
  - name: NEO4J | Patch settings /etc/neo4j/neo4j.properties
    lineinfile: dest=/etc/neo4j/neo4j.properties regexp="{{item.regexp}}" line="{{item.line}}"
    with_items: neo4j_properties
    notify: restart neo4j
    become: yes

  - name: NEO4J | Patch settings /etc/neo4j/neo4j-server.properties
    lineinfile: dest=/etc/neo4j/neo4j-server.properties regexp="{{item.regexp}}" line="{{item.line}}"
    with_items: neo4j_server_properties
    notify: restart neo4j
    become: yes
